# Generated by Django 5.2.6 on 2025-10-20 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DEAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "experiment_tag",
                    models.CharField(
                        blank=True,
                        help_text="Optional tag to link this DE analysis to other datasets",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("control_group", models.CharField(max_length=100)),
                ("treatment_group", models.CharField(max_length=100)),
                ("control_samples", models.JSONField()),
                ("treatment_samples", models.JSONField()),
                ("results_data", models.JSONField(help_text="DE results as JSON")),
                ("results_csv", models.TextField(help_text="Results as CSV string")),
                (
                    "metadata_csv",
                    models.TextField(blank=True, help_text="Sample metadata CSV"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("generated", "Generated in RN-able"),
                            ("uploaded", "Uploaded by user"),
                        ],
                        default="generated",
                        max_length=20,
                    ),
                ),
                (
                    "n_significant",
                    models.IntegerField(
                        default=0, help_text="Number of significant genes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="de_results",
                        to="core.analysissession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "-created_at"],
                        name="de_analysis_session_962aad_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PCAResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pca_coordinates",
                    models.JSONField(help_text="PC1, PC2 coordinates for each sample"),
                ),
                (
                    "pc1_variance",
                    models.FloatField(help_text="Variance explained by PC1"),
                ),
                (
                    "pc2_variance",
                    models.FloatField(help_text="Variance explained by PC2"),
                ),
                (
                    "plot_config",
                    models.JSONField(help_text="Complete Plotly figure configuration"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pca_result",
                        to="core.analysissession",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["session"], name="de_analysis_session_51a600_idx"
                    )
                ],
            },
        ),
    ]
