# Generated by Django 5.2.7 on 2025-10-30 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("de_analysis", "0002_remove_deanalysisresult_experiment_tag_and_more"),
    ]

    operations = []
