# Generated by Django 5.2.7 on 2025-10-31 03:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysissession",
            name="count_file_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="analysissession",
            name="metadata_file_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="analysissession",
            name="session_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                max_length=100,
                unique=True,
            ),
        ),
    ]
